---
title: "League Average Creator"
author: "Ben VanderWall"
date: "9/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

Input Dataframes
```{r}
drake <- read_excel("Data/Drake - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "Drake", .after = Date)
illinois_state <- read_excel("Data/Illinois State - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "Illinois State", .after = Date)
indiana_state <- read_excel("Data/Indiana State - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "Indiana State", .after = Date)
loyola <- read_excel("Data/Loyola - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "Loyola", .after = Date)
ue <- read_excel("Data/Purple Aces - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "UE", .after = Date)
siu <- read_excel("Data/SIU - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "SIU", .after = Date)
uni <- read_excel("Data/UNI - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "UNI", .after = Date)
valpo <- read_excel("Data/Valparaiso - 10.3.21.xlsx", na = "-") %>% 
            filter(row_number() <= n()-1) %>%
            mutate(Team = "Valpo", .after = Date)

data <- bind_rows(drake, illinois_state, indiana_state, loyola, ue, siu, uni, valpo) %>%
          select(-c(46, 49, 43))
data[is.na(data)] = 0

means <- summarise_all(data, mean)
data <- bind_rows(data, means)
```



