---
title: "Indiana State Data - 10_3_21"
author: "Ben VanderWall"
date: "9/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
data <- readxl::read_excel("Data/Indiana State - 10.3.21.xlsx", na = "-")
data <- data %>% filter(row_number() <= n()-1) %>%
          select(-c(42, 45, 48))
data[is.na(data)] = 0

form_mean <- function(col) {
  vec <- pull(data, col)
  vec2 <- pull(league, col)
  df <- tibble(Stats = col, 
               `Last 3` = mean(vec[1:3], na.rm = TRUE), 
               `Last 5` = mean(vec[1:5], na.rm = TRUE), 
               Season = mean(vec, na.rm = TRUE),
               League = mean(vec2, na.rm = TRUE),
               `Last 3 Difference` = `Last 3` - League,
               `Last 5 Difference` = `Last 5` - League,
               `Season Difference` = Season - League)
  df
}

df <- form_mean("Goals")
df2 <- form_mean("Shots")
df3 <- form_mean("Shots on target")
df4 <- form_mean("xG (Expected goals)")
df5 <- form_mean("xG conversion")
df6 <- form_mean("xG per shot")
df7 <- form_mean("xG per goal")
df8 <- form_mean("Corners")
df9 <- form_mean("Net xG (xG - Opponent's xG)")
df10 <- form_mean("Expected points")

attack_mean_table <- bind_rows(df,df2,df3,df4,df5,df6,df7,df8,df9,df10)
export_attacking_table <- bind_rows(df, df4, df5)

df <- form_mean("Passes")
df2 <- form_mean("Accurate passes")
df3 <- form_mean("Chances")
df4 <- form_mean("Chances successful")
df6 <- form_mean("Key passes")
df7 <- form_mean("Key passes accurate")
df8 <- form_mean("Crosses")
df9 <- form_mean("Crosses accurate")
df10 <- form_mean("Dribbles")
df11 <- form_mean("Dribbles successful")
df12 <- form_mean("Lost balls")
df13 <- form_mean("Lost balls in own half")
df14 <- form_mean("Entrances on opponent's half")
df15 <- form_mean("Entrances on final third of opponent's half")
df16 <- form_mean("Entrances to the opponent's box")

buildup_mean_table <- bind_rows(df,df2,df3,df4,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16)
export_buildup_table <- bind_rows(df3, df10, df14)

df <- form_mean("Attacks - left flank")
df2 <- form_mean("Attacks with shots - left flank")
df3 <- form_mean("Attacks - center")
df4 <- form_mean("Attacks with shots - center")
df5 <- form_mean("Attacks - right flank")
df6 <- form_mean("Attacks with shots - right flank")
df7 <- form_mean("Positional attacks")
df8 <- form_mean("Positional attacks with shots")
df9 <- form_mean("Counter-attacks")
df10 <- form_mean("Counter-attacks with a shot")
df11 <- form_mean("Set pieces attacks")
df12 <- form_mean("Attacks with shots - Set pieces attacks")
df13 <- form_mean("Free-kick attacks")
df14 <- form_mean("Free-kick attacks with shots")
df15 <- form_mean("Corner attacks")
df16 <- form_mean("Corner attacks with shots")

attack_typology_mean_table <-
  bind_rows(df,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16)

df <- form_mean("Challenges")
df2 <- form_mean("Challenges won")
df3 <- form_mean("Attacking challenges")
df4 <- form_mean("Attacking challenges won")
df5 <- form_mean("Defensive challenges")
df6 <- form_mean("Defensive challenges won")
df7 <- form_mean("Air challenges")
df8 <- form_mean("Air challenges won")
df9 <- form_mean("Tackles")
df10 <- form_mean("Tackles successful")
df11 <- form_mean("Fouls")
df12 <- form_mean("Ball recoveries")
df13 <- form_mean("Ball recoveries in opponent's half")
df14 <- form_mean("Ball interceptions")
df15 <- form_mean("Free ball pick ups")
df16 <- form_mean("Team pressing")
df17 <- form_mean("Opponent's xG")
df18 <- form_mean("Opponent's xG per shot")

defense_mean_table <- 
  bind_rows(df,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,
            df18)
export_defensive_table <- bind_rows(df, df16, df17)
```

```{r}
attack_mean_table
attack_typology_mean_table
buildup_mean_table
defense_mean_table
```

```{r}
write_csv(export_attacking_table, file = "Attack Table.csv")
write_csv(export_buildup_table, file = "Buildup Table.csv")
write_csv(export_defensive_table, file = "Defense Table.csv")
```

